### ISSUE TITLE
Translate in English

### ISSUE THREAD

**Issue by Logan1x** [Emil-501/The-Road-to-SDN#4]
Sir, I would Request you to please Translate this course material in english so that Other's can also read and understand this. Thanks.

**Comment by chenxiang2019** [comment]
Hello.
We would translate some of these materials(that is README.md and `数据中心`) to English soon. In this repo, most of these materials that are written in English could be found on Google.

**Comment by Logan1x** [comment]
Ok thanks @Wasdns

**Comment by Logan1x** [comment]
Should I translate what i can? @Wasdns

**Comment by chenxiang2019** [comment]
@Logan1x Of course. :)
